-- SHOW ALL CUSTOMER RECORDS
 SELECT * FROM CUSTOMERS; 
 
 -- SHOW TOTAL NUMBER OF CUSTOMERS
SELECT COUNT(*) FROM CUSTOMERS;

-- SHOW ALL TRANSACTIONS FOR CHENNAI MARKET 
SELECT * FROM TRANSACTIONS WHERE MARKET_CODE = 'Mark001';

-- SHOW PRODUCT CODES THAT WERE ESOLD IN CHENNAI
SELECT DISTINCT PRODUCT_CODE FROM TRANSACTIONS WHERE MARKET_CODE ='Mark001';

-- SHOW TRANSACTIONS WHERE CURRENCY IN USD
SELECT * FROM TRANSACTIONS WHERE CURRENCY='USD';

-- SHOW DIFFERENT CUSTOMER TYPE AVAILABLE
SELECT DISTINCT CUSTOMER_TYPE FROM CUSTOMERS;

-- SHOW DIFFERENT PRODUCT TYPE AVAILABLE
SELECT DISTINCT PRODUCT_TYPE FROM PRODUCTS;

-- SHOW TRANSACTIONS IN 2020
SELECT 
TRANSACTIONS.*,DATE.* 
FROM TRANSACTIONS 
INNER JOIN DATE 
ON TRANSACTIONS.ORDER_DATE = DATE.DATE 
WHERE YEAR=2020;

-- SHOW TOTAL REVENUE IN 2020
SELECT 
SUM(TRANSACTIONS.SALES_AMOUNT) AS TOTAL_REVENUE 
FROM TRANSACTIONS 
INNER JOIN DATE ON TRANSACTIONS.ORDER_DATE = DATE.DATE
WHERE DATE.YEAR =2020 AND TRANSACTIONS.CURRENCY ='INR\r' OR TRANSACTIONS.CURRENCY ='USD\r'; 

-- SHOW TOTAL REVENUE IN 2020 AND IN FEBRUARY
SELECT 
SUM(TRANSACTIONS.SALES_AMOUNT) AS TOTAL_REVENUE ,DATE.MONTH_NAME AS MONTH
FROM TRANSACTIONS 
INNER JOIN DATE ON TRANSACTIONS.ORDER_DATE = DATE.DATE
WHERE DATE.YEAR =2020 AND DATE.MONTH_NAME ="FEBRUARY" AND (TRANSACTIONS.CURRENCY ='INR\r' OR TRANSACTIONS.CURRENCY ='USD\r'); 

-- SHOW TOTAL REVENUE IN YEAR 2020 IN CITY CHENNAI
SELECT 
SUM(TRANSACTIONS.SALES_AMOUNT) AS TOTAL_REVENUE 
FROM TRANSACTIONS 
INNER JOIN DATE ON TRANSACTIONS.ORDER_DATE = DATE.DATE
WHERE DATE.YEAR =2020 AND TRANSACTIONS.MARKET_CODE ="Mark001";

 -- SHOW EACH CUSTOMERS SALE QUANTITY 
SELECT
 CUSTOMERS.CUSTMER_NAME,COUNT(TRANSACTIONS.SALES_QTY) AS TOTAL_SALES_QUANTITY 
 FROM CUSTOMERS
INNER JOIN TRANSACTIONS ON CUSTOMERS.CUSTOMER_CODE = TRANSACTIONS.CUSTOMER_CODE 
GROUP BY CUSTMER_NAME 
ORDER BY TOTAL_SALES_QUANTITY DESC;

-- END




